posts:
    path: /posts
    controller: App\Controller\ApiController::getAllPosts
    methods:    GET

post:
    path: /posts/{id}
    controller: App\Controller\ApiController::getPost
    methods:    GET
    requirements:
        id: '\d+'
